require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/seed.rb'
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/schema.rb'
Layout/LineLength:
  Max: 220
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false