default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# production:
#   <<: *default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    database: primary_database
    username: root
    password: <%= ENV['ROOT_PASSWORD'] %>
    adapter: postgresql
    encoding: unicode
  primary_replica:
    database: primary_database
    username: root
    password: <%= ENV['ROOT_READONLY'] %>
    adapter: postgresql
    replica: true
    encoding: unicode
  secondary_replica:
    database: secondary_database
    username: readonly_user
    password: <%= ENV['SECONDARY_READONLY_PASSWORD'] %>
    adapter: postgresql
    replica: true
    encoding: unicode