name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Bump version to') # Only run if commit contains "Bump version to"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Change to match your Ruby version

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-server-ip >> ~/.ssh/known_hosts

      - name: Deploy with Capistrano
        run: bundle exec cap production deploy
