name: Deploy

on:
  workflow_run:
    workflows: ["bump_version"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'  

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 178.79.141.148 >> ~/.ssh/known_hosts

      - name: Deploy with Capistrano
        run: bundle exec cap production deploy
